-- MySQL Script generated by MySQL Workbench
-- Qui 19 Nov 2015 17:44:58 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema a14034
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a14034
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a14034` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `a14034` ;

-- -----------------------------------------------------
-- Table `a14034`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `salario` FLOAT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT 'monitor',
  `cpf` VARCHAR(11) NOT NULL,
  `sexo` VARCHAR(9) NULL,
  `idGerente` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`, `idGerente`),
  INDEX `fk_Funcionario_Funcionario1_idx` (`idGerente` ASC),
  CONSTRAINT `fk_Funcionario_Funcionario1`
    FOREIGN KEY (`idGerente`)
    REFERENCES `a14034`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a14034`.`Atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Atracao` (
  `idAtracao` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `dataManutencao` DATE NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`idAtracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a14034`.`TrabalhaEm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`TrabalhaEm` (
  `idFuncionario` INT NOT NULL,
  `idAtracao` INT NOT NULL,
  `dataInicio` DATE NULL,
  PRIMARY KEY (`idFuncionario`, `idAtracao`),
  INDEX `fk_Funcionario_has_Atracao_Atracao1_idx` (`idAtracao` ASC),
  INDEX `fk_Funcionario_has_Atracao_Funcionario_idx` (`idFuncionario` ASC),
  CONSTRAINT `fk_Funcionario_has_Atracao_Funcionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `a14034`.`Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Funcionario_has_Atracao_Atracao1`
    FOREIGN KEY (`idAtracao`)
    REFERENCES `a14034`.`Atracao` (`idAtracao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a14034`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Loja` (
  `idLoja` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NULL,
  PRIMARY KEY (`idLoja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a14034`.`Loja_has_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Loja_has_Funcionario` (
  `idLoja` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  `dataInicio` DATE NULL,
  PRIMARY KEY (`idLoja`, `idFuncionario`),
  INDEX `fk_Loja_has_Funcionario_Funcionario1_idx` (`idFuncionario` ASC),
  INDEX `fk_Loja_has_Funcionario_Loja1_idx` (`idLoja` ASC),
  CONSTRAINT `fk_Loja_has_Funcionario_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `a14034`.`Loja` (`idLoja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Loja_has_Funcionario_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `a14034`.`Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a14034`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Produto` (
  `idProduto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `marca` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `a14034`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Estoque` (
  `idLoja` INT NOT NULL,
  `Produto_idProduto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`idLoja`, `Produto_idProduto`),
  INDEX `fk_Loja_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  INDEX `fk_Loja_has_Produto_Loja1_idx` (`idLoja` ASC),
  CONSTRAINT `fk_Loja_has_Produto_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `a14034`.`Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Loja_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `a14034`.`Produto` (`idProduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
