-- MySQL Script generated by MySQL Workbench
-- Thu 23 Jun 2016 10:48:26 AM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema a14034
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema a14034
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `a14034` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `a14034` ;

-- -----------------------------------------------------
-- Table `a14034`.`Atracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Atracao` (
  `idAtracao` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `tipo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `dataManutencao` DATE NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idAtracao`),
  UNIQUE INDEX `idAtracao_UNIQUE` (`idAtracao` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Produto` (
  `idProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `marca` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `tipo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Loja` (
  `idLoja` INT(11) NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `nome` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `local` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`idLoja`),
  UNIQUE INDEX `idLoja_UNIQUE` (`idLoja` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Estoque` (
  `idLoja` INT(11) NOT NULL,
  `idProduto` INT(11) NOT NULL,
  `quantidade` DOUBLE NOT NULL,
  PRIMARY KEY (`idLoja`, `idProduto`),
  INDEX `fk_Loja_has_Produto_Produto1_idx` (`idProduto` ASC),
  INDEX `fk_Loja_has_Produto_Loja1_idx` (`idLoja` ASC),
  CONSTRAINT `fk_Loja_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `a14034`.`Produto` (`idProduto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Loja_has_Produto_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `a14034`.`Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Funcionario` (
  `idFuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sobrenome` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `salario` FLOAT NOT NULL,
  `cargo` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT 'monitor',
  `cpf` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `sexo` VARCHAR(9) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `idGerente` INT(11) NOT NULL,
  PRIMARY KEY (`idFuncionario`, `idGerente`),
  UNIQUE INDEX `idFuncionario_UNIQUE` (`idFuncionario` ASC),
  INDEX `fk_Funcionario_Funcionario1_idx` (`idGerente` ASC),
  CONSTRAINT `fk_Funcionario_Funcionario1`
    FOREIGN KEY (`idGerente`)
    REFERENCES `a14034`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Venda` (
  `idVenda` INT(11) NOT NULL,
  `idFuncionario` INT(11) NOT NULL,
  `idLoja` INT(11) NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_Venda_Funcionario1_idx` (`idFuncionario` ASC),
  INDEX `fk_Venda_Loja1_idx` (`idLoja` ASC),
  UNIQUE INDEX `idVenda_UNIQUE` (`idVenda` ASC),
  CONSTRAINT `fk_Venda_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `a14034`.`Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venda_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `a14034`.`Loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`ItemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`ItemVenda` (
  `Venda_idVenda` INT(11) NOT NULL,
  `Produto_idProduto` INT(11) NOT NULL,
  `quantidadeProduto` DOUBLE NOT NULL,
  PRIMARY KEY (`Venda_idVenda`, `Produto_idProduto`),
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`Venda_idVenda` ASC),
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`Produto_idProduto` ASC),
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `a14034`.`Venda` (`idVenda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `a14034`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`Loja_has_Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`Loja_has_Funcionario` (
  `idLoja` INT(11) NOT NULL,
  `idFuncionario` INT(11) NOT NULL,
  `dataInicio` DATE NOT NULL,
  PRIMARY KEY (`idLoja`, `idFuncionario`),
  INDEX `fk_Loja_has_Funcionario_Funcionario1_idx` (`idFuncionario` ASC),
  INDEX `fk_Loja_has_Funcionario_Loja1_idx` (`idLoja` ASC),
  CONSTRAINT `fk_Loja_has_Funcionario_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `a14034`.`Loja` (`idLoja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Loja_has_Funcionario_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `a14034`.`Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `a14034`.`TrabalhaEm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`TrabalhaEm` (
  `idFuncionario` INT(11) NOT NULL,
  `idAtracao` INT(11) NOT NULL,
  `dataInicio` DATE NOT NULL,
  PRIMARY KEY (`idFuncionario`, `idAtracao`),
  INDEX `fk_Funcionario_has_Atracao_Atracao1_idx` (`idAtracao` ASC),
  INDEX `fk_Funcionario_has_Atracao_Funcionario_idx` (`idFuncionario` ASC),
  CONSTRAINT `fk_Funcionario_has_Atracao_Funcionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `a14034`.`Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Funcionario_has_Atracao_Atracao1`
    FOREIGN KEY (`idAtracao`)
    REFERENCES `a14034`.`Atracao` (`idAtracao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

USE `a14034` ;

-- -----------------------------------------------------
-- Placeholder table for view `a14034`.`atracoes_ativas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`atracoes_ativas` (`nome` INT, `tipo` INT, `idAtracao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `a14034`.`estoque_da_loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`estoque_da_loja` (`Nome_Loja` INT, `Nome_Produto` INT, `quantidade` INT, `idProduto` INT);

-- -----------------------------------------------------
-- Placeholder table for view `a14034`.`visao_trabalha_em`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `a14034`.`visao_trabalha_em` (`nome` INT, `sobrenome` INT, `salario` INT, `nomeAtracao` INT);

-- -----------------------------------------------------
-- function aumento_salario
-- -----------------------------------------------------

DELIMITER $$
USE `a14034`$$
CREATE DEFINER=`a14034`@`%` FUNCTION `aumento_salario`(salario double, aumento double) RETURNS double
BEGIN
	RETURN salario * aumento;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function contata_especialista
-- -----------------------------------------------------

DELIMITER $$
USE `a14034`$$
CREATE DEFINER=`a14034`@`%` FUNCTION `contata_especialista`(cargo varchar(50)) RETURNS int(11)
BEGIN
	DECLARE id integer;
    
    SELECT idFuncionario into id 
    FROM Funcionario f
    WHERE f.cargo like cargo
    ORDER BY RAND() LIMIT 1;
    
    RETURN id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `a14034`.`atracoes_ativas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a14034`.`atracoes_ativas`;
USE `a14034`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`a14034`@`%` SQL SECURITY DEFINER VIEW `a14034`.`atracoes_ativas` AS select `a14034`.`Atracao`.`nome` AS `nome`,`a14034`.`Atracao`.`tipo` AS `tipo`,`a14034`.`Atracao`.`idAtracao` AS `idAtracao` from `a14034`.`Atracao` where (`a14034`.`Atracao`.`status` = 1);

-- -----------------------------------------------------
-- View `a14034`.`estoque_da_loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a14034`.`estoque_da_loja`;
USE `a14034`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`a14034`@`%` SQL SECURITY DEFINER VIEW `a14034`.`estoque_da_loja` AS select `l`.`nome` AS `Nome_Loja`,`p`.`nome` AS `Nome_Produto`,`e`.`quantidade` AS `quantidade`,`p`.`idProduto` AS `idProduto` from ((`a14034`.`Loja` `l` join `a14034`.`Estoque` `e`) join `a14034`.`Produto` `p`) where ((`l`.`idLoja` = `e`.`idLoja`) and (`e`.`idProduto` = `p`.`idProduto`));

-- -----------------------------------------------------
-- View `a14034`.`visao_trabalha_em`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `a14034`.`visao_trabalha_em`;
USE `a14034`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`a14034`@`%` SQL SECURITY DEFINER VIEW `a14034`.`visao_trabalha_em` AS select `f`.`nome` AS `nome`,`f`.`sobrenome` AS `sobrenome`,`f`.`salario` AS `salario`,`a`.`nome` AS `nomeAtracao` from ((`a14034`.`Funcionario` `f` join `a14034`.`Atracao` `a`) join `a14034`.`TrabalhaEm` `t`) where ((`f`.`idFuncionario` = `t`.`idFuncionario`) and (`t`.`idAtracao` = `a`.`idAtracao`));
USE `a14034`;

DELIMITER $$
USE `a14034`$$
CREATE
DEFINER=`a14034`@`%`
TRIGGER `a14034`.`atribui_mecanico`
AFTER UPDATE ON `a14034`.`Atracao`
FOR EACH ROW
begin
    IF(new.status = 0) THEN
		INSERT INTO TrabalhaEm(idFuncionario, idAtracao, dataInicio) 
        values ((SELECT idFuncionario FROM Funcionario WHERE cargo like 'mecanico' ORDER BY RAND() LIMIT 1), new.idAtracao, now());
	END IF;
END$$

USE `a14034`$$
CREATE
DEFINER=`a14034`@`%`
TRIGGER `a14034`.`demite_funcionario`
AFTER UPDATE ON `a14034`.`Loja`
FOR EACH ROW
begin
	if(old.local <> new.local) THEN
		DELETE FROM Loja_has_Funcionario WHERE new.idLoja = idLoja;
	END IF;
END$$

USE `a14034`$$
CREATE
DEFINER=`a14034`@`%`
TRIGGER `a14034`.`bonus_salario`
AFTER INSERT ON `a14034`.`TrabalhaEm`
FOR EACH ROW
begin
    if((SELECT COUNT(*) FROM TrabalhaEm WHERE idFuncionario = new.idFuncionario) > 1) THEN
   	 UPDATE Funcionario SET salario = aumento_salario(salario,2.0)
     WHERE idFuncionario = new.idFuncionario;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
