/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.atualizacao;

import banco.BDController;
import classes.Loja;

/**
 *
 * @author Hugo
 */
public class AtualizacaoLoja extends javax.swing.JFrame {

    private BDController bDController;
    private Loja loja;

    /**
     * Creates new form AtualizacaoLoja
     */
    public AtualizacaoLoja(int idLoja) {
        initComponents();

        setTitle("Atualize um Funcionário");

        preencheCampos(idLoja);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void preencheCampos(int id) {
        this.bDController = new BDController();
        this.loja = bDController.selectLoj
                
        jTextField1.setText(loja.getNome());
        jTextField2.setText(loja.getSobrenome());
        jTextField3.setText(loja.getSalario());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
