/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.funcions;

import banco.BDController;
import java.sql.SQLException;

/**
 *
 * @author Hugo
 */
public class SolicitaFucnionario extends javax.swing.JFrame {
    private BDController bDController;

    /**
     * Creates new form SolicitaFucnionario
     */
    public SolicitaFucnionario(String cargo) {
        initComponents();
        
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        
        setTitle("Funcionários Solicitados");
        
        preencheCampo(cargo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void preencheCampo() throws ClassNotFoundException, SQLException {
        this.bDController = new BDController();
        
        Funcionario funcionario = bDController.contataEspecialista(cargo);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
